# Example GitHub Pages configuration settings
title: Christ University Lavasa - Product Design Challenge
description: A challenge website for students to solve real-world issues.
theme: minima  # You can choose any supported theme or leave it out for a custom theme